### ISSUE TITLE
Add option to only see people who are online

### ISSUE THREAD

**Issue by wiki-me** [typestruck/merochat#232]
What i would like is to be able to have something that is like bar, where when you feel like chatting with people and you could just go there.

I use wusoup.com and it is the only feature i feel is really missing.  Plus i made someone there try merochat and she said she felt there was no one on merochat, showing people only online might fix that impression.

**Comment by easafe** [comment]
Hello @wiki-me ,

Thanks for the suggestion. There is already a similar issue: https://github.com/typestruck/mero-issues/issues/60

That would indeed be useful but right now my focus is on getting more users (as much as I am bad at marketing). However, if you feel like thats something you could do, I can help with getting a PR made.

**Comment by wiki-me** [comment]
> That would indeed be useful but right now my focus is on getting more users (as much as I am bad at marketing). However, if you feel like thats something you could do, I can help with getting a PR made.

I don't think that is the best approach , most of the efforts should be for developing the software , because "good products sell themselves", merochat is already listed on [alternativeto](https://alternativeto.net/software/merochat/), and [according](https://github.com/liberapay/liberapay.com/issues/269) to liberapay it is one of their top referrers so people should be trying out the platform, the idea is to try to make those early adopters stay and bring in more users and the way to do that is to have best platform you can have.

I have a suggestion if your interested, if this will be implemented i could then add a good review on alternativeto and slant.co (I already [created a question](https://www.slant.co/improve/topics/29978/~websites-for-finding-people-to-talk-to) asking for places to talk online) , i have a few more ideas about where to put links to this project that will hopefully bring in more users once i will feel i can honestly recommend it.  

Hopefully if the platform is good and the data is collected we could start seeing metrics showing the platform is growing organically (something like lemmy on [the federation](https://the-federation.info/platform/73) or [fediverse observer](https://lemmy.fediverse.observer/stats) , where even when the active users count was not growing the number of servers which is probably a metric for the usage of early adopters was steadly growing).

**Comment by easafe** [comment]
> "good products sell themselves"

MeroChat is a chat website; there is no much point in having features if there is no one to talk to. Most of the efforts for developing the software have already been made.

> I have a suggestion if your interested, if this will be implemented i could then add a good review on alternativeto and slant.co

You are welcome to leave a review if you wish but this one particular feature isn't what gonna make it break or not. The current suggestion sorting is already taking last seen into account so if it feels like there isn't anyone new online then it might just as well be there is no one new online 🙃

**Comment by wiki-me** [comment]
> MeroChat is a chat website; there is no much point in having features if there is no one to talk to.

Lets look at lemmy as a case study, a while ago i was looking for an open source alternative to reddit, I looked at the list of [open source reddit alternatives](https://alternativeto.net/software/reddit/?license=opensource) and liked lemmy the most because of it's feature set, despite its active users count not growing (but the server count was) i kept posting content despite not having interesting content there and the comments were not really interesting, then reddit API fiasco happened, a lot of users where looking for a new platform and now lemmy has more content for Linux and open source then reddit (At least for the communities i subscribe to).

So a good feature set can attract early adopters, I can't promise it but if this will be implemented i will check it out once in about two weeks for a while and see if there are people (adding myself as a user). besides the website already has users, maybe a part of the problem is that unlike in wusoup you don't get emails when someone messages you.

> Most of the efforts for developing the software have already been made.

Most of the work usually probably goes to building the basics, but it can be one "[killer feature](https://www.urbandictionary.com/define.php?term=Killer%20feature)" that can make the software popular.

> You are welcome to leave a review if you wish but this one particular feature isn't what gonna make it break or not.

I can't speak for other people or predict the future, but for me this is a feature i find really attractive and will make me want to check out the platform repeatedly and promote it. It's hard to tell (if not impossible) what will be popular and what won't, It happened to me before that i posted something on reddit thinking it would get 20 upvotes but it got more then a thousand.

> The current suggestion sorting is already taking last seen into account so if it feels like there isn't anyone new online then it might just as well be there is no one new online upside_down_face

It's still very unclear , i think in wusoup i sometimes have to clicks for something like a minute or two before finding someone online, and that could make or break the platform, the human brain is described as a "[cognitive miser](https://dictionary.apa.org/cognitive-miser)" and some wrote a book about UX design litterly called "[Don't Make Me Think](https://www.amazon.com/Dont-Make-Think-Revisited-Usability/dp/0321965515)".

**Comment by wiki-me** [comment]
Looks like you got back to work on this. maybe you could reopen and put it in the backlog? . this will also be useful if you checkout the website several times a day and will save a significant amount of time in the long run.

**Comment by easafe** [comment]
the suggestions have just been seriously improved. maybe i take a stab at this in some form or another

**Comment by wiki-me** [comment]
I see a show "only users online" checkbox was added but when i click on it it has no effect. is it supposed to work yet?

maybe open the issue and close it so i could test it out when it is ready?

Maybe instead of just showing "no users online" there could be a graph showing the number of online users given the hour and day of the week. this could be a average of the last year or 6 months.

**Comment by easafe** [comment]
there was a bug resetting the filter that has been fixed now. but it turns out that to work properly need to do some broader changes as well. at some point i will add auto pairing too

**Comment by easafe** [comment]
okay, I think this is working well enough now. next is finding users to be online :)

**Comment by wiki-me** [comment]
It looks good, maybe stuff like the checkbox could be a little more fancy (something like whats in [here](https://getcssscan.com/css-checkboxes-examples)) but i personally don't care about that.

another small polishing is to remember if i requested to only show who is online (it could be set in the browser storage). when visiting the site 3/4 times a day having to keep clicking on who is online can add up to a lot of time.
