### ISSUE TITLE
Let the user type their message when connectivity has been lost

### ISSUE THREAD

**Issue by Juggo0** [typestruck/merochat#235]
When the connection to the server is lost, the focus from the message text bar is immediately removed, and cannot be re-focused until connectivity is restored.
This is annoying behavior as the user might be mid writing a message, or might want to type, since losing connection shouldn't affect their ability to write.

It should be changed to either:
 - Have the ability to write, but not the ability to send the message until connection is restored. (Still a bit annoying, but much better)
 Or
 - Have the ability to send the message, but only actually be sent once the connection is restored. (Optimal solution)

**Comment by Juggo0** [comment]
Code responsible for this behavior is identified here:
https://github.com/Juggo0/merochat/blob/b847b17df84a3a60ee3a0f33dafefcba1757d39a/src/Shared/Im/View/ChatInput.purs#L131

My suggestion is to not disable the entire textarea, but just specifically the sending message feature. (This should also handle sending messages with the send button, instead of with enter.) (Currently you can send messages, even if the server is "down" with the button.)

**Comment by easafe** [comment]
You have to have a proper ux for this. Disabling enter or the button (and nothing else) would be confusing and make it look like it is broken. If you allow the user to send then it gets more complex you d need to keep track of messages to send on reconnect

**Comment by Juggo0** [comment]
Wouldn't throwing up a dialogue box, with "Please wait with sending the message while we try to reconnect you!" work?
Or something along that nature?

It would solve the issue with confusion. Thought it is just a temporary solution before implementing some kind of message queue system.

**Comment by easafe** [comment]
I think the easiest would be to rework the existing connection lost message

**Comment by Juggo0** [comment]
Okay, I'll cook up something, we'll see.
