### ISSUE TITLE
Example configuration for NGINX proxy in front of MeroChat

### ISSUE THREAD

**Issue by georgschilling** [typestruck/merochat#237]
I'm attempting a local installation of MeroChat behind an NGINX proxy. After I got around the problem with Google Capture, I'm now faced with the problem that I can't write to anyone. In the chat window, “Waiting for connection” is always displayed within the text field.

The NGINX is now in the most minimal configuration, this does not improve the situation.

Any help is welcome
George

**Comment by easafe** [comment]
Hello @georgschilling ,

You don't need nginx to run locally. But if you still want it as a reverse proxy you need to handle websockets on your nginx configuration file. Something like:

```
map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
}

server {
   location /ws {
        proxy_pass http://localhost:1339;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection  $connection_upgrade;
        proxy_set_header Host $host;
        proxy_read_timeout 86400;
    }

    location / {
            proxy_pass http://localhost:8000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $host;
    }
}
```

**Comment by Skeeve4711** [comment]
Hello @easafe,

we tried that configuration but we still get an error in our development console in safari and also in firefox:
[blocked] The page at https://host.name/im was not allowed to run insecure content from ws://host.name:1339/.

Do you have any idea on why it still tries to connect to to ws:// and not wss://?

Best regards,
Pascal

**Comment by easafe** [comment]
https://github.com/typestruck/merochat/blob/master/src/Client/Im/WebSocket.purs#L22

You will likely run into other problems as well. Production is ad hoc to how it runs online now and thus not documented
