### ISSUE TITLE
Always show failed to send message status 

### ISSUE THREAD

**Issue by easafe** [typestruck/merochat#268]
Display failed to send message status regardless if user has message receipts enabled to not

**Comment by Juggo0** [comment]
Currently statuses are all just a type, defined [here](https://github.com/Juggo0/merochat/blob/b847b17df84a3a60ee3a0f33dafefcba1757d39a/src/Shared/Im/Types.purs#L553) .
And when assembling the chat window, this part of the code is used to either add statuses or not [here](https://github.com/Juggo0/merochat/blob/b847b17df84a3a60ee3a0f33dafefcba1757d39a/src/Shared/Im/View/ChatHistory.purs#L79). (Or at least I think so)
This means that all types are just ignored all together without any consideration for the actual value. 

So, `failed to send` could be a special case that we check for, when deciding to include it into the html or not. (Not sure if we can just update the html on the fly like that tho)

The other option I can think of, is to make `failed to send` it's own type/whatever and include it by default as an empty string which changes into the current message upon detecting that the message failed to send.

So something like:
```
instance Show MessageSuccessStatus where
      show = case _ of
            Errored → "Failed to send"
            Success → ""
```

**Comment by easafe** [comment]
`MessageStatus` is the relevant type https://github.com/Juggo0/merochat/blob/b847b17df84a3a60ee3a0f33dafefcba1757d39a/src/Shared/Im/Types.purs#L94

```
data MessageStatus
      = Errored
      | Sent
      | Received
      | Delivered
      | Read
```

Being a sum type, the status can only be one of those options at a time. So there is no need to separate `Errored` from there.

The bit that shows the status on the screen is https://github.com/Juggo0/merochat/blob/b847b17df84a3a60ee3a0f33dafefcba1757d39a/src/Shared/Im/View/ChatHistory.purs#L114

`HE.span (HA.class' { hidden: incomingMessage || noReadReceipts }) $ show status` 

As you can see if `noReadReceipts` is true then the hidden class is added and the element is not shown. The easy fix is to included Errored on noReadReceipts -- i.e. ignore user preferences if `status == Errored`

**Comment by Juggo0** [comment]
Pr: https://github.com/typestruck/merochat/pull/272
