### ISSUE TITLE
Suggestion improvements

### ISSUE THREAD

**Issue by easafe** [typestruck/merochat#288]
When picking suggestions circle through the following categories:

* Primary: users not yet chatted who have been online in the last week sorted by bin, last online
* Secondary: users not yet chatted who have been online in the last two weeks sorted by bin last online
* Tertiary: users not yet chatted who have been online in the last month sorted by bin, last online
* Fallback: all users sorted by score, last online

If more than 60% of returned users for a given category are in the bottom 3 bins or no users are returned for that category, move to the next category.

**Comment by Iizuki** [comment]
This in contrast to the current state of affairs, (as I understand it):

- Primary: users not yet chatted sorted by last online, score
- Secondary: users you've already chatted with (practically never shown)

**Comment by easafe** [comment]
Right now all users are just sorted by talked to, last online, score which makes users you chatted before very last

**Comment by easafe** [comment]
Lets put @Juggo0 on this
